from tornados.tasks.prequential import Prequential
from tornados.tasks.prequential_drift import PrequentialDrift
from tornados.tasks.prequential_drift_evaluator import PrequentialDriftEvaluator
from tornados.tasks.prequential_learner_detector_pairs import PrequentialMultiPairs